### PR TITLE
Implement mobileauth update

### PR DESCRIPTION
**Pull request by tschbc**

### CODE REVIEW

**Comment by f-w** [comment]
@tschbc , your branch is not based on the tip of master. Can you do a `git fetch && git rebase master`?

**Comment by tschbc** [comment]
@f-w  is it fine to use the "Rebase and merge" option in this PR? It looks like it does the same thing without needing to create a new PR.

**Comment by f-w** [comment]
> @f-w is it fine to use the "Rebase and merge" option in this PR? It looks like it does the same thing without needing to create a new PR.

@tschbc, No need to create a new PR. Just commit the change to branch implement-mobileauth-update.

**Review by f-w — APPROVED** [review]
Tested working e2e.

**Pull request merged**
